### ISSUE TITLE
The first time launch StageManger with window snapshot broken

### ISSUE THREAD

**Issue by linitfor** [awaescher/StageManager#4]
Hi developer,

I found everytime to first launch the stage manger. The first create scene window on the left hand side show the broken window snapshot. We need to active every window again to get the whole picture. Is there any good idea to fix this issue ?

**Comment by awaescher** [comment]
Yeah, this is for minimized windows only. Windows won't draw minimized windows so I'd have to normalize them first.
That again would result in ugly flickering. Maybe I should move them to -10000;-10000 and back to do so. 
However, I did not (yet).

**Comment by linitfor** [comment]
Will you continue to improve it ? It is real interest. I am not good at this part coding. Hence, I don't know how to fix it.

**Comment by awaescher** [comment]
This repo is a proof of concept and was made purely for fun - before StageManager from Apple was released. Now that I worked with StageManager on macOS and iPadOS, I feel it's sadly not that good as I was expecting it to be.
So at the moment I am not planning to do much in this repository.

By the way I did not investigate too much into polishing the screenshot tech because I planned to use DWM thumbnails that render the real window content live. So that you can see videos and animations moving there as well.
However, it seems that DWM thumbnails **1)** need a window handle to get rendered on which WPF does not give to its controls (unlike WinForms) and **2)** DWM thumbnails cannot be tilted in 3D which is important to the look and feel of StageManager.
